checks:
  - 'dummy://'
  - kind: random
    target: A
    title: Random A
    name: random-a
  - kind: random
    target: A
    title: Random B
    name: random-b
  - kind: random
    name: random
    title: Random
    visible: false
  - kind: ping
    target: aaseq.com
    name: ping
    title: AASeq ping
    timeout: 0.1
  - kind: get
    target: https://aaseq.com
    title: aaseq.com (GET)
    period: 30
    timeout: 0.1
    break: true
  - kind: head
    target: https://aaseq.com
    title: aaseq.com (HEAD)
    period: 30
  - kind: GET
    target: http://localhost:11080/healthz/random
    title: Random Health Probe
    success: 3
    failure: 2
  - kind: TCP
    target: aaseq.com:80
    title: TCP
    period: 10
    timeout: 0.001
  - kind: COMPOSITE
    title: Composite Random
    target: random random-a random-b
    percent: 50

web:
  prefix: http://*:11080/
  title: Status
  refresh: 1

logging:
  console: verbose
