checks:
  - 'dummy://'
  - target: random://A
    title: Random A
  - target: random://B
    title: Random B
  - target: random://
    name: random
    title: Random
  - name: ping
    title: AASeq ping
    target: ping://aaseq.com
    timeout: 0.1
  - target: https://aaseq.com
    title: aaseq.com
    period: 30
    timeout: 0.1
  - title: Random Health Probe
    target: http://localhost:8089/healthz/random
    success: 3
    failure: 2

web:
  title: Status
  refresh: 10

logging:
  console: verbose
