checks:
  - 'dummy://'
  - kind: random
    target: A
    title: Random A
  - kind: random
    target: A
    title: Random B
  - kind: random
    name: random
    title: Random
    visible: false
  - kind: ping
    target: aaseq.com
    name: ping
    title: AASeq ping
    timeout: 0.1
  - kind: get
    target: https://aaseq.com
    title: aaseq.com (GET)
    period: 30
    timeout: 0.1
    break: true
  - kind: head
    target: https://aaseq.com
    title: aaseq.com (HEAD)
    period: 30
  - kind: GET
    target: http://localhost:8089/healthz/random
    title: Random Health Probe
    success: 3
    failure: 2

web:
  prefix: http://*:8089
  title: Status
  refresh: 1

logging:
  console: verbose
